---
title: "Tidy Data"
params:
  number: 1
  purpose: 'The purpose of this assignment is to introduce yourself to the "tidy data" concept and to practice modifying data frames between long and wide formats in R.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Software

If you haven't yet, go to the [Course Software](../software.html) page and install all the software we'll need for this course. You'll need these tools for this assignment.

# 2. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 3. Readings & Exercises

- **Getting Familiar with the Course**: Follow [Snoop's advice](https://www.youtube.com/watch?v=Tnlaokj1opA) and read the entire [Course Syllabus](../syllabus.html) (actually read the whole thing). Then review the [schedule](../schedule.html) and make sure to note important upcoming deadlines.
- **Getting Familiar with Tidy Data**: Read [this tidyverse article](https://tidyr.tidyverse.org/articles/tidy-data.html) explaining the concept of tidy data. In your ``r hw_file``, copy some of the examples into a code chunk and run them to see the results of converting data between long and wide formats.
- **Use AI to Practice Reshaping Messy Data**: Open [ChatGPT](https://chat.openai.com/), [Claude](https://claude.ai/), or whatever AI tools you prefer and start a chat to practice the concept of reshaping data into long and wide formats. Ask the AI questions about what it gives you to make sure you understand the concept. Are you certain the AI is giving you good code? Play around with it and see if chatting with the AI is helpful. Include the link to your chat in your submission if you have one. Here is an example prompt (feel free to experiment with other prompts):

> `I'm practicing the concept of tidy data in R. Provide me an example dataset in wide format and then show me R code for how to convert it to long format. Afterwards, do the opposite - show me an example of a dataset in long format and show me R code for how to convert it to wide format.  In each case, explain your reasoning first, then show me the code.`

#### **Optional**

- [Chapter 6](https://r4ds.hadley.nz/data-tidy.html) in Hadley Wickham's R4DS book covers more detail on the concept of tidy data with even more examples. It's worth reading through for a more comprehensive understanding.
- [Chapter 3](https://yardbook.jhelvy.com/tidy-data) in the YARDBook also covers tidy data.
- [Chapter 29](https://r4ds.hadley.nz/quarto.html#code-chunks) in Hadley Wickham's R4DS book is a great introduction to [Quarto](https://quarto.org/). I highly recommend taking a look through it to get a better understanding of Quarto (we'll be using it the whole semester!).

# 4. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing? Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

If you're unsure where to start with a reflection, try filling out this template:

> "I used to think ______, now I think ______ 🤔"

# 5. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
