---
title: "Project Workshop"
params:
  number: 10
  purpose: 'The purpose of this assignment is to....'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Make a Plan

Next week we will have a full-day in-class workshop to work on our projects. To prepare, instead of reading about new content, you should dedicate some time to meet with your team and make a plan for class next week.

**We will have 2.5 hours** - how are you going to use that time? Focus on things that require coordination across your team, and otherwise work on individual tasks and check each others' work. Write out your plan by following these guidelines:

- Read through the feedback you received from your progress report.
- Write down a bullet list of goals to achieve for your final report. Consider these questions. If any apply to your team, add that item to your plan:
    - Do you need to modify your research question?
    - Do you need other data sources to address all of the questions you have asked?
    - Have you appropriately cleaned / prepared your data?
    - Are you unsure about any code you've written (e.g. cleaning, joining data, making charts, etc.)? Would it be helpful to have Professor Helveston or one of the class TAs help review your code?
    - Teams often separate tasks by person - for your coding tasks, have your other teammates reviewed the code you wrote to check for bugs?
    - Is there a particular chart you've been working on but haven't quite yet figured out how to code it up?
    - Is there a _better version_ of a chart you want to work on improving?
    - If you're feeling confident about some parts of the analysis thus far, have you tried polishing up any charts? What can you do to an existing chart to make it communicate a message better?
    - Review the content on visualizing information from weeks 6 - 11. Were there any specific types of charts that you think might work well with your project?

These are just some guidelines to consider - there may be other questions to ask yourself.

You should come up with your own list an include it here in your reflection. Bring your list with you to class so you can share it with your team. Once your teammates all agree, we can then break out and execute individual tasks towards moving your projects to the finish line!

# 3. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
