---
title: "Exploring Data"
params:
  number: 3
  purpose: 'The purpose of this assignment is to develop some basic strategies for exploring data sets to gain a greater understanding of the variable types as well as key relationships such as centrality, variability, and correlation'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Read & Practice

- [R4DS - 7: Exploratory data analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html): Provides some more "hands on" strategies for exploring data using R and the **ggplot2** library.
- [Wilke - 12: Visualizing associations](https://clauswilke.com/dataviz/visualizing-associations.html): An overview of ways to visualize associations between two or more variables.
- ["Beware Spurious Correlations", Harvard Business Review](https://hbr.org/2015/06/beware-spurious-correlations)
- Watch [this 20 minute video](https://www.youtube.com/watch?v=zHcQPKP6NpM) to learn about some basic data types and descriptive statistics.
- Watch [this 15 minute video](https://www.youtube.com/embed/fmK5YWWobH8) to learn about the basics of correlation measures.

### Choosing the right chart

You will want to choose different chart types depending on the relationship or message you want to convey. Fortunately, there are lots of great guides to help you make those choices. 

- View a quick overview of many common plot types in [Wilke - 5: Directory of visualizations](https://clauswilke.com/dataviz/directory-of-visualizations.html).
- View the course site [help page](https://eda.seas.gwu.edu/2024-Fall/references.html#choosing-the-right-chart) on choosing the right chart.

### Optional readings

The history of statistical correlation is rather ugly and routed in racism and eugenics. These readings discuss this topics in more detail:

- [Francis Galton pioneered scientific advances in many fields – but also founded the racist pseudoscience of eugenics](https://theconversation.com/francis-galton-pioneered-scientific-advances-in-many-fields-but-also-founded-the-racist-pseudoscience-of-eugenics-144465)
- [Column: The false, racist theory of eugenics once ruled science. Let’s never let that happen again](https://www.pbs.org/newshour/nation/column-the-false-racist-theory-of-eugenics-once-ruled-science-lets-never-let-that-happen-again)
- Listen to [this Radiolab episode](https://podcasts.apple.com/us/podcast/g-unfit/id152249110?i=1000444689017) on eugenics.

# 3. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing? Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

Some thoughts you may want to try in your reflection:

- "I used to think ______, now I think ______ 🤔"
- Discuss some of the key insights or things you found interesting in the readings or recent class periods.
- Connect the course content to your own work or project you're working on.

# 4. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected? 
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
