---
title: "Visualizing Information"
params:
  number: 4
  purpose: 'The purpose of this assignment is to learn what makes a "good" information visualization, which is _not_ entirely a subjective judgment. There are a wide variety of design principles available to help guide the creation of clear, effective information visualizations, many of which are rooted in research on human psychology.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Read & Practice

> "Data visualization is part art and part science. The challenge is to get the art right without getting the science wrong and vice versa."
>
> -- Claus O. Wilke in [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/introduction.html)

### Readings on visualizing information

These two chapters cover a lot of excellent examples of what makes a chart "good" and "bad"---the focus of what we'll talk about in class next week:

- [Healy 1: Look at Data](http://socviz.co/lookatdata.html#lookatdata): What makes figures good and bad
- [Wilke 1: Introduction](https://clauswilke.com/dataviz/introduction.html): Definitions of "ugly", "bad", and "wrong" figures

### Video on the psychology of data viz

Watch [this 40-minute video](https://www.youtube.com/watch?v=fSgEeI2Xpdc) titled "How humans see data", by John Rauser. He discusses how we can exploit our understanding of human psychology to design effective charts (I'll cover much of the same information in the video in class next week).

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/fSgEeI2Xpdc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>

# 3. Make a chart

Go to the [Data to Viz](https://www.data-to-viz.com/) website and find a visualization that you find interesting. Then click on "R Graph Gallery" to view an example of how to make that types of chart in R using ggplot. In a code chunk, replicate that code and see if you can get it to run on your machine.

# 4. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing?

Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

Some thoughts you may want to try in your reflection:

- Write about one of the best (or worst) data visualizations you've seen.
- "I used to think ______, now I think ______ 🤔"
- Discuss some of the key insights or things you found interesting in the readings or recent class periods.
- Connect the course content to your own work or project you're working on.

# 5. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
