---
title: "Comparisons"
params:
  number: 6
  purpose: 'The purpose of this assignment is to learn some of the technical details of how to create charts for **comparing values** to one another and / or to a benchmark.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Readings

> "At the heart of quantitative reasoning is a single question: Compared to what?"
>
> -- Edward Tufte

Most of the readings this week have code in them that illustrate how to create each chart type, and I encourage you to try and reproduce a few of the examples provided in R yourself. You may also want to take a look at the [top 50 ggplots](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html), which contains examples with ggplot code to create 50 common visualizations.

- [Slope charts](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Slope%20Chart)
- [Bullet charts](https://themockup.blog/posts/2020-11-29-bullet-chart-variants-in-r/)
- [Dumbell charts](http://uc-r.github.io/cleveland-dot-plots)
- Wilke: [7 - Visualizing distributions](https://clauswilke.com/dataviz/histograms-density-plots.html)
- Wilke: [9 - Visualizing many distributions at once](https://clauswilke.com/dataviz/boxplots-violins.html)
- [Dual-Scaled Axes in Graphs - Are They Ever the Best Solution?](http://www.perceptualedge.com/articles/visual_business_intelligence/dual-scaled_axes.pdf)

# 3. Make a Chart

Once you've read through everything, add a code chunk in your ``r hw_file`` file that creates one of the charts you saw in one of the readings. **Cite the source** of the chart. The goal is to try and reproduce the chart as closely as possible to how it looks in the reading. While it is okay to copy-paste code directly into your reflection, try to write the code yourself. Practicing the coding yourself is key to mastering these skills. You may need to modify the figure dimensions in the chunk settings.

# 4. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing?

Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

Some thoughts you may want to try in your reflection:

- Write about one of the best (or worst) data visualizations you've seen.
- "I used to think ______, now I think ______ 🤔"
- Discuss some of the key insights or things you found interesting in the readings or recent class periods.
- Connect the course content to your own work or project you're working on.

# 5. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
