---
title: "Polishing Charts"
params:
  number: 8
  purpose: 'The purpose of this assignment is to learn some techniques for adding "polish" to your charts. We will start choosing colors and fonts more carefully, and we will also annotate our charts with informative text.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Readings

This week we'll get into the weeds with techniques for polishing up your charts. This is a critically important step for making your charts easy for others to understand and effective as a central tool for communicating important results. It's also where you can be highly creative!

- How to polish ggplot charts: [R4DS Chapter 28 - Graphics for communication](https://r4ds.had.co.nz/graphics-for-communication.html)
- Wilke: [4 - Color scales](https://clauswilke.com/dataviz/color-basics.html)
- Rost: [Which color scale to use when visualizing data](https://blog.datawrapper.de/which-color-scale-to-use-in-data-vis/)

# Optional

- Wilke: [21 - Multi-panel figures](https://clauswilke.com/dataviz/multi-panel-figures.html)
- Check out the [patchwork package](https://patchwork.data-imaginist.com/articles/patchwork.html) for merging multiple charts together
- How to make a multi-panel [figure with a shared legend](https://wilkelab.org/cowplot/articles/shared_legends.html).
- Check out this [tool](https://github.com/clauswilke/colorblindr) for simulating color blindness.
- Check out these tools for customizing your Rmd file: [PIMP my Rmd](https://holtzy.github.io/Pimp-my-rmd/)

# 3. Practice polishing

Go back to a previous figure you've made somewhere - in class, in a previous homework, etc. Using some of the principles in the readings you just read, try to make a more polished version of your figure. Can you customize the fonts? colors? Annotate it? Try to make a chart that is publication-ready.

# 4. Reflect

> **This week, include in your reflection an image or link to a chart you've seen that you felt was really well-polished**

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing?

Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

Some thoughts you may want to try in your reflection:

- Write about an interesting data visualization about trends you've seen.
- "I used to think ______, now I think ______ 🤔"
- Discuss some of the key insights or things you found interesting in the readings or recent class periods.
- Connect the course content to your own work or project you're working on.

# 5. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
