name: Render and Deploy Quarto Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  #  Use Ubuntu runner (not macOS)

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages(c("tidyverse", "knitr", "rmarkdown", "here", "gsheet", "kableExtra", "cowplot", "ggrepel", "viridis"))
        shell: Rscript {0}

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
