name: Render and Deploy Quarto Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ~/.local/R/library

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Create R library path
        run: mkdir -p ~/.local/R/library

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgit2-dev \
            libxml2-dev \
            libcurl4-openssl-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Query R dependencies
        run: |
          options(download.file.method = "libcurl")
          options(repos = "https://cran.rstudio.com")
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-r-4.4-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ubuntu-r-4.4-

      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          options(repos = "https://cran.rstudio.com")
          install.packages(c(
            "tidyverse", "here", "gsheet", "kableExtra", "cowplot", "ggrepel", 
            "viridis", "rmarkdown", "knitr", "remotes"
          ))
          remotes::install_github("gadenbuie/xaringanExtra")
        shell: Rscript {0}

      - name: Confirm tidyverse is installed
        run: |
          library(tidyverse)
          sessionInfo()
        shell: Rscript {0}

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
          force_orphan: true
