name: Render and Deploy Quarto Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ faster and more reliable than macOS

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R packages
        run: |
          install.packages(c(
            "tidyverse", "here", "gsheet", "kableExtra", "cowplot", "ggrepel", 
            "viridis", "rmarkdown", "knitr", "remotes"
          ))
          remotes::install_github("gadenbuie/xaringanExtra")
        shell: Rscript {0}

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
